export const CREATE_USER_USECASE_PROXY = Symbol('CREATE_USER_USECASE_PROXY');

export const UPDATE_USER_USECASE_PROXY = Symbol('UPDATE_USER_USECASE_PROXY');

export const GET_ALL_USER_USECASE_PROXY = Symbol('GET_ALL_USER_USECASE_PROXY');